version: 2
workflows:
  experiment-workflow:
    steps:
      -
        name: "Corona"
        command: experiment.run_single_node
        params:
          command: python data.py & python main.py
          container: paperspace/dl-containers:pytorch-py36-cu100-jupyter
          experimentEnv:
            EPOCHS_EVAL: 5
            EVAL_SECS: 10
            MAX_STEPS: 1000
            TRAIN_EPOCHS: 20
          machineType: p2.xlarge
          modelPath: /model
          modelType: PyTorch
          name: gradientci-sample
          clusterId: clbdo1h0q
        checks: #[optional]
          tensorflow:loss:
            target: "0.0..0.5"
            aggregate: "mean"
          defaults: #[optional]
            precision: 3
      triggers:
        branches:
          ignore: irrelevant-branch
        tags:
          only:
            - v.*
            - latest