name: Greetings

on: [pull_request, issues, push, watch]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Congratulations! You have opened your first issue in the Corona_Detection Project.'
        pr-message: 'Congratulations on your first pull request creation in the Corona_Detection Project.'
        push-message: 'Congratulations on your first push into the Corona_Detection Project. Hope you will contribute more often.'
        watch-message: 'Thank You for you interest in the Corona_Detection Project'
